### PR TITLE
Added building with CMake and packaging with CPack

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by loumalouomega** [comment]
I am sorry, but I keep this only as "mirror" of the last release for another project. I prefer to keep it as it is. What is the point of this PR?

**Comment by loumalouomega** [comment]
Additionally if I change the current structure of the files my compilations will fail

**Comment by KOLANICH** [comment]
>but I keep this only as "mirror" of the last release for another project. I prefer to keep it as it is. What is the point of this PR?

OK, no point then. I just evaluating various CLI args parsing libraries and have even created an abstraction layer around them (and it makes any sense only if all the libs properly packaged). Sent here probabbly because the original author doesn't use git.

**Comment by loumalouomega** [comment]
> > but I keep this only as "mirror" of the last release for another project. I prefer to keep it as it is. What is the point of this PR?
> 
> OK, no point then. I just evaluating various CLI args parsing libraries and have even created an abstraction layer around them (and it makes any sense only if all the libs properly packaged). Sent here probabbly because the original author doesn't use git for that project.

I prefer to stay "virgin", thanks for the contribution. I am not related to the project, and I don't think is the best CLI parser neither. If you do your own repository it will be as official as mine.

**Pull request closed without merging**
